//! Remote signing abstraction used by the tunnel client.
//!
//! The client never touches raw private key material. Instead it holds an
//! `Arc<dyn TunnelKey>` that can be asked for a public key and to sign
//! arbitrary messages. Adapter types in this module bridge that trait to
//! the concrete `SigningKey` interfaces demanded by `rcgen` (for cert/CSR
//! generation) and `rustls` (for TLS handshake signatures).
//!
//! Supported algorithms: Ed25519 and ECDSA P-256. Extend `KeyAlgorithm` to add more.
//! Note: Let's Encrypt does not support Ed25519 CSRs, so ECDSA P-256 is the default
//! for new keypairs generated by the CLI.

use anyhow::Result;
use rcgen::{
    PublicKeyData as RcgenPublicKeyData, SignatureAlgorithm, SigningKey as RcgenSigningKey,
};
use rustls::pki_types::SubjectPublicKeyInfoDer;
use rustls::sign::{Signer as RustlsSigner, SigningKey as RustlsSigningKey};
use rustls::{Error as RustlsError, SignatureAlgorithm as RustlsSigAlg, SignatureScheme};
use std::fmt::Debug;
use std::sync::Arc;

/// Signature algorithm exposed by a [`TunnelKey`].
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum KeyAlgorithm {
    Ed25519,
    EcdsaP256,
}

impl KeyAlgorithm {
    fn rcgen_sig_alg(&self) -> &'static SignatureAlgorithm {
        match self {
            KeyAlgorithm::Ed25519 => &rcgen::PKCS_ED25519,
            KeyAlgorithm::EcdsaP256 => &rcgen::PKCS_ECDSA_P256_SHA256,
        }
    }

    fn rustls_scheme(&self) -> SignatureScheme {
        match self {
            KeyAlgorithm::Ed25519 => SignatureScheme::ED25519,
            KeyAlgorithm::EcdsaP256 => SignatureScheme::ECDSA_NISTP256_SHA256,
        }
    }

    fn rustls_alg(&self) -> RustlsSigAlg {
        match self {
            KeyAlgorithm::Ed25519 => RustlsSigAlg::ED25519,
            KeyAlgorithm::EcdsaP256 => RustlsSigAlg::ECDSA,
        }
    }

    /// OID under which the public key is published in an SPKI
    /// AlgorithmIdentifier.
    /// - Ed25519 (RFC 8410): 1.3.101.112
    /// - ecPublicKey + P-256 (RFC 5480): 1.2.840.10045.2.1 with param 1.2.840.10045.3.1.7
    fn spki_oid(&self) -> &'static [u64] {
        match self {
            KeyAlgorithm::Ed25519 => &[1, 3, 101, 112],
            // For EC, the top-level alg OID is ecPublicKey; the curve OID is
            // encoded as the algorithm parameter (handled in build_spki).
            KeyAlgorithm::EcdsaP256 => &[1, 2, 840, 10045, 2, 1],
        }
    }

    /// Named-curve OID to include as the AlgorithmIdentifier parameter.
    /// `None` for algorithms that don't need a parameter (e.g. Ed25519).
    fn spki_curve_oid(&self) -> Option<&'static [u64]> {
        match self {
            KeyAlgorithm::Ed25519 => None,
            KeyAlgorithm::EcdsaP256 => Some(&[1, 2, 840, 10045, 3, 1, 7]),
        }
    }
}

/// Abstract keypair whose private key stays on the other side of an FFI
/// boundary. Implementations must be thread-safe because rustls may call
/// `sign` from multiple handshake threads concurrently.
pub trait TunnelKey: Send + Sync + Debug {
    fn algorithm(&self) -> KeyAlgorithm;

    /// Raw public key bytes. For Ed25519 this is the 32-byte public key.
    fn public_key_raw(&self) -> Vec<u8>;

    /// Sign `msg` with the private key. For ECDSA schemes the implementation
    /// is expected to hash `msg` with the hash implied by the scheme; for
    /// Ed25519 no pre-hashing is required.
    fn sign(&self, msg: &[u8]) -> Result<Vec<u8>>;
}

/// Build the DER-encoded SubjectPublicKeyInfo from raw key bytes + algorithm.
pub(crate) fn build_spki(alg: KeyAlgorithm, raw_public_key: &[u8]) -> Vec<u8> {
    use yasna::models::ObjectIdentifier;
    let oid = ObjectIdentifier::from_slice(alg.spki_oid());
    let curve_oid = alg.spki_curve_oid().map(ObjectIdentifier::from_slice);
    yasna::construct_der(|w| {
        w.write_sequence(|w| {
            w.next().write_sequence(|w| {
                w.next().write_oid(&oid);
                if let Some(c) = curve_oid.as_ref() {
                    w.next().write_oid(c);
                }
            });
            w.next()
                .write_bitvec_bytes(raw_public_key, raw_public_key.len() * 8);
        });
    })
}

/// Adapter exposing a `TunnelKey` through rcgen's SigningKey trait.
pub struct RcgenRemoteKey {
    inner: Arc<dyn TunnelKey>,
    raw_pub: Vec<u8>,
}

impl RcgenRemoteKey {
    pub fn new(inner: Arc<dyn TunnelKey>) -> Self {
        let raw_pub = inner.public_key_raw();
        Self { inner, raw_pub }
    }
}

impl RcgenPublicKeyData for RcgenRemoteKey {
    fn der_bytes(&self) -> &[u8] {
        &self.raw_pub
    }

    fn algorithm(&self) -> &'static SignatureAlgorithm {
        self.inner.algorithm().rcgen_sig_alg()
    }
}

impl RcgenSigningKey for RcgenRemoteKey {
    fn sign(&self, msg: &[u8]) -> std::result::Result<Vec<u8>, rcgen::Error> {
        self.inner
            .sign(msg)
            .map_err(|_| rcgen::Error::RingUnspecified)
    }
}

/// Adapter exposing a `TunnelKey` through rustls' SigningKey trait.
#[derive(Debug)]
pub struct RustlsRemoteKey {
    inner: Arc<dyn TunnelKey>,
    spki: Vec<u8>,
}

impl RustlsRemoteKey {
    pub fn new(inner: Arc<dyn TunnelKey>) -> Self {
        let spki = build_spki(inner.algorithm(), &inner.public_key_raw());
        Self { inner, spki }
    }
}

impl RustlsSigningKey for RustlsRemoteKey {
    fn choose_scheme(&self, offered: &[SignatureScheme]) -> Option<Box<dyn RustlsSigner>> {
        let scheme = self.inner.algorithm().rustls_scheme();
        if offered.contains(&scheme) {
            Some(Box::new(RustlsRemoteSigner {
                inner: Arc::clone(&self.inner),
                scheme,
            }))
        } else {
            None
        }
    }

    fn public_key(&self) -> Option<SubjectPublicKeyInfoDer<'_>> {
        Some(SubjectPublicKeyInfoDer::from(self.spki.as_slice()))
    }

    fn algorithm(&self) -> RustlsSigAlg {
        self.inner.algorithm().rustls_alg()
    }
}

#[derive(Debug)]
struct RustlsRemoteSigner {
    inner: Arc<dyn TunnelKey>,
    scheme: SignatureScheme,
}

impl RustlsSigner for RustlsRemoteSigner {
    fn sign(&self, message: &[u8]) -> std::result::Result<Vec<u8>, RustlsError> {
        self.inner
            .sign(message)
            .map_err(|e| RustlsError::General(format!("tunnel key sign failed: {e}")))
    }

    fn scheme(&self) -> SignatureScheme {
        self.scheme
    }
}
